### ISSUE TITLE
Still being maintained / updated?

### ISSUE THREAD

**Issue by kvnxiao** [mum4k/termdash#222]

**Comment by mum4k** [comment]
Hello @kvnxiao, yes termdash is still maintained although there is currently no active development on it.

Do you have anything specific in mind?

**Comment by kvnxiao** [comment]
I was simply wondering if there was a roadmap of sorts, since the README states that the API is non-stable until 1.0.0, and currently it's only at 0.10.0.

**Comment by mum4k** [comment]
That is a good question. I was refraining from marking the API stable until we get all the main features in. You can take a look at the currently filed issues, those that are marked as enhancement indicate potential new features:

https://github.com/mum4k/termdash/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

Out of these probably only one has the potential to break the API - addition of floating / pop-up windows:
https://github.com/mum4k/termdash/issues/104

On the other hand I do understand the importance of having a stable API and we do have users now, so I could be convinced otherwise, i.e. to release 1.0 and make only compatible changes. It is a balancing act. I started mapping what we should do before we release 1.0, but didn't get far:
https://github.com/mum4k/termdash/issues/193

Feel free to contribute to the discussion and thank you for your time.

**Comment by mum4k** [comment]
Closing as answered, please feel free to reopen if you have further questions, or comment directly in #193.
