### ISSUE TITLE
when i use idea debug model

### ISSUE THREAD

**Issue by godla** [mum4k/termdash#233]
open /dev/tty: device not configured

how to fix?

**Comment by mum4k** [comment]
Hello @godla, I suspect that is because idea debug model doesn't provide termdash with access to a real terminal (/dev/tty is a terminal access device). termdash uses termbox-go to draw on a real terminal.

If you just need to debug something, I would suggest using the fake terminal implementation:

https://github.com/mum4k/termdash/tree/master/private/faketerm

This will allow you to run any code including widgets without them writing onto a real terminal. They write into a cell buffer in memory instead. This is used in multiple unit tests throughout the code base, so there should be plenty of examples.

Please let me know if you have more questions.

**Comment by godla** [comment]
thanks
