### ISSUE TITLE
Background Execution

### ISSUE THREAD

**Issue by 1995parham** [mum4k/termdash#246]
Is there any way to send a program to the background (with `ctrl + z` for example) then resume it? When I use this key combination on Linux nothing happens. Is there any suggestion for this?

**Comment by keithknott26** [comment]
I normally run it inside a screen session which works fine when you open the session back up

**Comment by 1995parham** [comment]
By screen session, you mean something like `tmux`?

**Comment by keithknott26** [comment]
on a linux host you can (provided screen is installed) and type "screen" which will open a new terminal inside your terminal... run your program, and then hit ctrl + a then "d" for detach.   Then your program will run in the background, when you're ready to return to it just type "screen -x "

**Comment by 1995parham** [comment]
Ok, I have got it. `tmux` is also like that. Thanks for mentioning. :+1:  But in a case that I don't use it can we put it into the background?

**Comment by mum4k** [comment]
Hi @1995parham and thank you @keithknott26 for providing the useful hint.

The reason ctrl+z doesn't work is that the underlying terminal library (tcell or termbox) captures all keyboard input. So the ctrl+z that is pressed is captured by Termdash instead of making it to the underlying shell that would then suspend the application.

If I remember correctly, what ctrl+z does is that it instructs the shell to send SIGTSTP to the process to essentially suspend it.

We could emulate the behavior by defining ctrl+z as a shortcut at the Termdash level. For that, you could implement a [keyboard subscriber](https://github.com/mum4k/termdash/wiki/Termdash-API#termdashkeyboardsubscriber) that will react to this shortcut being pressed. The reaction could be that the Go program will send SIGTSTP to itself. There is some example code : this Go issue: https://github.com/golang/go/issues/776#

Please let me know if you would like more details or if you have further questions.
