### ISSUE TITLE
add dim text style as cell.Option

### ISSUE THREAD

**Issue by icy-comet** [mum4k/termdash#328]
I noticed that `termdash/cell` maps one-to-one to the styles provided by the `tcell` API.
https://github.com/mum4k/termdash/blob/f13e4222fa62b251e937fa2a00ffab003d814f13/terminal/tcell/cell_options.go#L59-L75

However, the ["dim" style from the tcell package](https://pkg.go.dev/github.com/gdamore/tcell/v2#Style.Dim) is missing from this mapping.  If this is not a deliberate decision, adding the style would be a "nice-to-have".

**Comment by mum4k** [comment]
Hi @icy-comet, thank you for pointing this out. I suspect this is because the "dim" style isn't supported by [termbox](https://github.com/nsf/termbox), which was the initial terminal driver termdash was built upon. We can add the "dim" style and just make the appropriate disclaimers and error messages when termbox is being used.

Is this something you are interested in contributing?
